### ISSUE TITLE
java.lang.AbstractMethodError when searching in REI

### ISSUE THREAD

**Issue by yesn0t** [Queerbric/Inspecio#58] opened 2022-01-11 04:10 UTC
game crashes when i search in REI (may be related to #56 ?)
using inspecio 1.2.1+1.18 and REI 7.1.357 

<details> <summary> [crash logs here] </summary>

```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 11/01/2022, 04:24
Description: Getting tooltips

java.lang.AbstractMethodError: Receiver class net.minecraft.class_1420 does not define or inherit an implementation of the resolved method 'abstract void method_35170(net.minecraft.class_2487)' of interface net.minecraft.class_5761.
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.9)
	at io.github.queerbric.inspecio.tooltip.EntityTooltipComponent.adjustEntity(EntityTooltipComponent.java:148)
	at io.github.queerbric.inspecio.tooltip.SpawnEntityTooltipComponent.of(SpawnEntityTooltipComponent.java:52)
	at net.minecraft.item.SpawnEggItem.getTooltipData(SpawnEggItem:544)
	at net.minecraft.item.ItemStack.getTooltipData(ItemStack:104)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:351)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:208)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:85)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:217)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:202)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:186)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:61)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:49)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.queerbric.inspecio.tooltip.EntityTooltipComponent.adjustEntity(EntityTooltipComponent.java:148)
	at io.github.queerbric.inspecio.tooltip.SpawnEntityTooltipComponent.of(SpawnEntityTooltipComponent.java:52)
	at net.minecraft.class_1826.method_32346(class_1826.java:544)

-- Screen details --
Details:
	Screen name: net.minecraft.class_490
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:49)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:43)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:231)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:85)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:217)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:202)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:186)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:61)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:49)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 0
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: minecraft:bat_spawn_egg

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: bat_spawn_egg
	Item Damage: 0
	Item NBT: {}
	Item Foil: false

-- Screen details --
Details:
	Screen name: net.minecraft.class_490

-- Search entry details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 0
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: minecraft:bat_spawn_egg

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: bat_spawn_egg
	Item Damage: 0
	Item NBT: {}
	Item Foil: false

-- Affected screen --
Details:
	Screen name: net.minecraft.class_490

-- Affected level --
Details:
	Chunk stats: 361, 206
	Level dimension: minecraft:overworld
	Level spawn location: World: (-112,64,208), Section: (at 0,0,0 in -7,4,13; chunk contains blocks -112,-64,208 to -97,319,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Server brand: fabric
	Server type: Integrated singleplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.11.12-300.fc34.x86_64
	Java Version: 17.0.1, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
	Memory: 605136912 bytes (577 MiB) / 1744830464 bytes (1664 MiB) up to 1744830464 bytes (1664 MiB)
	CPUs: 4
	Virtual memory max (MB): 11763.33
	Virtual memory used (MB): 6339.59
	Swap memory total (MB): 7842.00
	Swap memory used (MB): 62.93
	JVM Flags: 2 total; -Xms1024m -Xmx1664m
	Fabric Mods: 
		adb: Accessible Dev Blocks ${version}
		advancednetherite: Advanced Netherite 1.3.1-1.18.1
		allstackable: All Stackable 1.5.1-1.18.1
		always-drop-loot: Always Drop Loot 5.1.0+mc1.17.1
		architectury: Architectury 3.2.51
		auto_third_person: Auto Third Person 1.1.0
		axesareweapons: Axes Are Weapons 1.5.1
		balm-fabric: Balm 2.4.0+0
		basicshields: Basic Shields [Fabric] 1.2.1-1.18.1
		bettercontrols: Better Controls 1.2.3
		betterf3: BetterF3 1.2.1
		betterfpsdist: Better FPS distance Mod 1.18-1.3
		betterrsqrt: Better `rsqrt` 1.0.1
		betterthanmending: BetterThanMending 1.3.0
		block_of: Block Of... 1.0.4
		blue_endless_jankson: jankson 1.2.1
		boat_step_up: Boat Step Up 1.2.1
		bobby: Bobby 3.1.0
		borderlessmining: Borderless Mining 1.1.1+1.18
		brb: Better Recipe Book 1.5.6
		cadentis: Cadentis 1.1+1.18
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		cenchants: Combat Enchants 1.10.3
		charcoalplus: Charcoal+ 1.18.1-1.1.1
		chat_heads: Chat Heads 0.6.0
		chatlagfix: Chat lag fix 1.0.0
		clienttweaks: Client Tweaks 7.0.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_yaml: yaml 3.6.5
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.0
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.0
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0
		com_github_reviversmc_modget-lib: modget-lib 3.0.0
		com_github_reviversmc_modget-manifest-api_compat: compat 0.2.1
		com_github_reviversmc_modget-manifest-api_spec3: spec3 0.2.1
		com_github_reviversmc_modget-manifest-api_spec4: spec4 0.2.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		combustibleentities: CombustibleEntities 1.0.0
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		configurable_recipes: Configurable Recipes 1.0.5
		controlling: Controlling For Fabric 9.0.4
		cpas: cpas 3.0.0
		cpas-api: cpas-api 3.0.0
		cpas-runtime: cpas-runtime 3.0.0
		cpas-trinkets: cpas-trinkets 3.0.0
		craftingcraft: CraftingCraft 11.0.1
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cullleaves: Cull Leaves 2.3.2
		customlan: Custom LAN 1.18-v2.0.1
		customspawns: Custom Spawns 0.6+1.18
		deepslateinstamine: Deepslate Instamine 1.3
		denseores: Dense Ores: Refabricated 1.2.1+1.18.1
		dynamicfps: Dynamic FPS 2.0.6
		easiervillagertrading: EasierVillagerTrading 1.18-fabric0.43.1-1.5.4
		elytranofall: ElytraNoFall 1.18.1-Fabric-v1.0.1
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		entity-view-distance: Entity View Distance 1.0.0
		extendedhotbar: ExtendedHotbarRebared 3.0.1
		fabric: Fabric API 0.45.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957165
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.6+533be9ba65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5565
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fabricshieldlib: Fabric Shield Lib 1.4.5-1.18
		food_enhancements: Food Enhancements fabric-1.17.1-1.5.1
		fuelinfo: FuelInfo 1.0-SNAPSHOT
		fullscreeno: fullscreeNO 1.0.0
		gbfabrictools: GBfabrictools 1.3.4+1.18
		hh: Huntingham Hills 1.3.12
		iknowwhatimdoing: I Know What I'm Doing 4.0.0
		inspecio: Inspecio 1.2.1+1.18
		inventory_control_tweaks: Inventory Control Tweaks 1.3.12+MC1.18-1.18.1
		inventoryessentials: Inventory Essentials 4.0.0
		inventorypause: Inventory Pause 1.0.7
		invmove: InvMove 1.18-0.1.0
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		java: OpenJDK 64-Bit Server VM 17
		kbootstrap: kbootstrap 0.2.1
		krypton: Krypton 0.1.6
		ksyxis: Ksyxis 1.1
		kyrptconfig: Kyrpt Config 1.3.4-1.18
		lazydfu: LazyDFU 0.1.2
		leaves_us_in_peace: Leaves Us In Peace 1.0+MC1.18-1.18.1
		limitless: limitless 1.6.1
		logprot: Logprot Mod 1.18-1.5
		malilib: MaLiLib 0.10.0-dev.26
		mcg: MCG 1.2.6
		midashunger: Midas Hunger 2.0.0+1.18.1
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.18.1
		minimalmenu: MinimalMenu 1.18.1-0.1.4
		miningcooldownfix: Mining Cooldown Fix 1.18.1-1.0.0
		mob_catcher: Mob Catcher 1.1.20
		modget: Modget 0.4.3+1.17
		modget-core: Modget Core 0.4.3
		modmenu: Mod Menu 3.0.1
		moretotems: More Totems 2.9.0
		morevillagers-fabric: MoreVillagersFabric 3.1.0-SNAPSHOT
		mousetweaks: Mouse Tweaks 2.16
		multiconnect: MultiConnect 1.5.7
		multiconnect-api: MultiConnect API 1.5.7
		nacl: Not Another Config Library 0.9.3
		nbttooltip: NBT Tooltip 1.5.0-fabric
		net_auoeke_extensions_asm-tree: asm-tree 0.37.1
		net_auoeke_extensions_extensions: extensions 0.37.1
		net_auoeke_reflect: reflect 4.2.0
		net_gudenau_lib_unsafe: unsafe 1.6.1
		netherportalfix: NetherPortalFix 9.0.0
		ngv: Nether Gold Veins 1.0.0
		no-telemetry: No Telemetry 1.3.0
		noaispawneggs: NoAISpawnEggs 10.0.1
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18
		nyfsquiver: Nyf's Quivers Fabric-0.4.0-1.18
		omega-config: OmegaConfig 1.0.8
		onastick: On A Stick 2.0.0
		org_apache_commons_commons-text: commons-text 1.9
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		org_yaml_snakeyaml: snakeyaml 1.29
		owo: oωo 0.3.12+1.18
		oxidized: Oxidized 1.5.1
		perfectaccuracy: Perfect Accuracy 1.2
		pigsteel: Pigsteel Mod 1.7.0
		polymorph: Polymorph 0.0.18-1.18.1
		popenchanttags: PopEnchantTagsResuscitated 1.1.0
		powershot: Powershot 1.4.0-1.18-fabric
		quickshulker: Quick Shulker 1.3.3-1.18
		recipecache: recipecache 0.2.1-1.17.1
		roughlyenoughitems: Roughly Enough Items 7.1.357
		shulkerutils: shulkerutils 1.0.4-1.18
		skeletonfix: Skeleton Aiming Fix 1.1.1+1.18
		soft_togglesneak: Soft_ToggleSneak 1.1.1
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		tiefix: TieFix 1.8.0
		torchbowmod: TorchBowMod 1.0
		trashslot: TrashSlot 11.0.1
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.1.0
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.1-1.18.1
		usabledragonsbreath: UsableDragonsBreath 1.0.0
		vanilla_disable: Vanilla Disable 1.0.2
		vanilla_essence: Vanilla essence 3.0.1-1.18.X
		vanillashears: Vanilla Shears 1.18.1-0.1.0
		wi_zoom: WI Zoom 1.3-MC1.18
		worldtime: WorldTime 1.18-fabric0.43.1-1.3.1
	Launched Version: MultiMC5
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Current Language: English (US)
	Server Running: true
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0

	Suspected Mods: Inspecio (inspecio), Roughly Enough Items (roughlyenoughitems)

**Comment by LambdAurora** [comment] 2022-01-11 11:27
What the fuck

It says it cannot call the method `copyDataFromNbt` from the `Bucketable` interface on a `BatEntity`, but that doesn't make any sense???

```java
	protected static void adjustEntity(Entity entity, NbtCompound itemNbt, InspecioConfig.EntitiesConfig config) {
		if (entity instanceof Bucketable bucketable) {
			bucketable.copyDataFromNbt(itemNbt);
			if (entity instanceof PufferfishEntity pufferfish) {
				pufferfish.setPuffState(config.getPufferFishPuffState());
			} else if (entity instanceof TropicalFishEntity tropicalFish) {
				if (itemNbt.contains("BucketVariantTag", NbtElement.INT_TYPE)) {
					tropicalFish.setVariant(itemNbt.getInt("BucketVariantTag"));
				}
			}
		}
	}
```

Like, it does check if it can use that method, there's no way for it to call it unless it does implement that interface????

Is there a mod that allows you to bucket bats?
This crash doesn't make any sense.

**Comment by LambdAurora** [comment] 2022-01-11 12:54
Ok, the issue is coming from the mod Vanilla Disable due to a bad mixin.

Not an Inspecio issue.

**Comment by yesn0t** [comment] 2022-01-11 16:05
thanks, my search query was "ba" for basic shields, sorry for wrong report i'll send this log to vanilla disable :pray:

**Comment by DragonEggBedrockBreaking** [comment] 2022-01-11 20:46
Fixed, and the source code has been pushed to GitHub. I will release it later this week, until then, there are GitHub actions builds that you can use. If you are unsure how to use them, ping me on discord.

**Comment by yesn0t** [comment] 2022-01-11 20:59
found and downloaded, will test , thank you both so much for the help and quick response :heart:

**Comment by DragonEggBedrockBreaking** [comment] 2022-01-11 23:20
> found and downloaded, will test , thank you both so much for the help and quick response ❤️

No problem - it was my bad for doing something quite stupid in my code, and it was quite an easy fix.

**Comment by LambdAurora** [comment] 2022-01-12 20:39
Fixed in the affected mod.

**Closed as completed by LambdAurora** 2022-01-12 20:39 UTC
Labels: other mod issue
