### ISSUE TITLE
No way to load on 1.16.5

### ISSUE THREAD

**Issue by horacehoff** [Queerbric/Inspecio#4] opened 2021-05-10 15:47 UTC
Hello (yes this is more of a feature request than an issue), could you port this mod to 1.16.5 ? Because right now this mod is very useful by the idea but not by the version(only releasing on snapshots isn't very useful...)

**Comment by Bluberry-Kat** [comment] 2021-05-10 15:48
dupe of #1, #2,
> Sadly, Inspecio uses a new system first introduced in Minecraft 1.17 snapshots. Reimplementing it on 1.16.5 would require a lot of time and effort that just isn't worth it.  

@LambdAurora maybe a pinned issue is worth consideration?

**Closed as completed** 2021-05-10 15:49 UTC
Labels: duplicate
